- hosts: all
  tasks:
    - name: rustup downloaded
      get_url:
        url: https://sh.rustup.rs
        dest: .
        force: no
        mode: 0775
      register: rustup_downloaded
    - name: install rust
      shell: ./rustup-init.sh -y
      #when: rustup_downloaded.changed is defined and rustup_downloaded.changed
    - name: scaphandre repository cloned 
      git:
        clone: yes
        depth: 1
        force: yes
        repo: https://github.com/hubblo-org/scaphandre.git
        dest: scaphandre
