- hosts: all
  tasks:
    - include_tasks: "include/validate_gh_input.yml"
    - name: rustup downloaded
      get_url:
        url: https://sh.rustup.rs
        dest: .
        force: no
        mode: 0775
      register: rustup_downloaded
    - name: rust installed
      shell: ./rustup-init.sh -y
      when: rustup_downloaded.changed is defined and rustup_downloaded.changed
