- hosts: all
  user: root
  tasks:
    - name: show parameters coming from github
      debug:
        msg: "Request coming from github: |
        actor: {{ github_actor | default('undefined') }}
        repo: {{ github_repository | default('undefined') }}
        workflow: {{ github_workflow | default('undefined') }} workspace: {{ github_workspace | default('undefined') }} event_name: {{ github_event_name | default('undefined') }} event_path: {{ github_event_path | default('undefined') }} 
        sha: {{ github_sha | default('undefined') }} 
        ref: {{ github_ref | default('undefined') }} 
        head_ref: {{ github_head_ref | default('undefined') }} 
        base_ref: {{ github_base_ref | default('undefined')}} 
        server_url: {{ github_server_url | default('undefined')}} 
        rpm_url: {{ github_rpm_url | default('undefined') }}
        "
    - fail:
        msg: Server URL is not authorized to run this job.
      when: github_server_url != "https://github.com"
    - fail:
        msg: Repository is not authorized to run this job.
      when: not "scaphandre" in github_repository
    - name: Ensure scaphandre package is purged
      community.general.apt_rpm:
        pkg: scaphandre
        state: absent
    - name: Get RPM package
      get_url:
        url: "{{ github_rpm_url }}"
        dest: .
      register: download
    - name: Install RPM package
      shell: "dnf install -y {{ download.dest }}" 
    - name: Check service state
      shell: systemctl status scaphandre
      register: result
    - name: Display error if failed
      fail:
        msg: "STDOUT: {{ result.stdout }} STDERR: {{ result.stderr }}"
      when: result.rc != 0
