- hosts: all
  tasks:
    - name: show parameters coming from github
      debug:
        msg: "Request coming from github: |
        actor: {{ github_actor | default('undefined') }} 
        repo: {{ github_repository | default('undefined') }} 
        workflow: {{ github_workflow | default('undefined') }} 
        workspace: {{ github_workspace | default('undefined') }} 
        event_name: {{ github_event_name | default('undefined') }} 
        event_path: {{ github_event_path | default('undefined') }} 
        sha: {{ github_sha | default('undefined') }} 
        ref: {{ github_ref | default('undefined') }} 
        head_ref: {{ github_head_ref | default('undefined') }} 
        base_ref: {{ github_base_ref | default('undefined')}} 
        server_url: {{ github_server_url | default('undefined')}} 
        "
    - fail:
        msg: Repository is not authorized to run this job.
      when: github_repository != "hubblo-org/scaphandre"
    - name: rustup downloaded
      get_url:
        url: https://sh.rustup.rs
        dest: .
        force: no
        mode: 0775
      register: rustup_downloaded
    - name: rust installed
      shell: ./rustup-init.sh -y
      when: rustup_downloaded.changed is defined and rustup_downloaded.changed
    - name: scaphandre repository cloned 
      git:
        clone: yes
        depth: 1
        force: yes
        repo: https://github.com/hubblo-org/scaphandre.git
        dest: scaphandre
    - name: build and run scaphandre
      shell: cd ~/scaphandre && cargo build && ./target/debug/scaphandre stdout -t 2 && cd ~
    - name: run unit tests
      shell: cd ~/scaphandre && cargo test --all
